spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password: admin1015*
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  session:
    store-type: redis
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true